### PR TITLE
Fix #2374 Don't exit fzf by SIGINT while executing command

### LINKED ISSUE #2374: Don't exit fzf by SIGINT while executing command
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Consider use execute action for the interactive command which is designed to be completed by SIGINT and so on.
For some actual use-case as an example, consider following log tailing fzf
```
fzf --bind 'ctrl-l:execute(tail -F {})' 
```

- Typing ctrl-l on the selecting file, it's getting into `tail -F file`.
- Want to exit tail command by Ctrl-C and go back to the fzf

Expected behavior
- Go back to the current fzf session, keeping input for fzf and current query and positions

Actual behavior
- Quit fzf too

fzf should be aware that it's executing a command, and shouldn't quit by some signals while executing.

This behavior is useful not only for the above single use-case but also for any kind of interactive command to cancel them by Ctrl-C.

See https://github.com/junegunn/fzf/pull/2375 also for the proposing fix

### PR DESCRIPTION
**Pull request by bitterfox**
Fix for #2374

### CODE REVIEW

**Review by junegunn — CHANGES_REQUESTED** [review]
Thanks. Please rebase your code to the current master branch and make sure that the gofmt check passes.

https://github.com/junegunn/fzf/blob/bb0502ff4429580e363be708ff301c35479144e3/Makefile#L69

**Comment by bitterfox** [comment]
Oh, thanks. Rebased and fixed gofmt :bowing_man:

File: src/terminal.go [hunk 1]
```diff
@@ -1837,8 +1843,13 @@ func (t *Terminal) Loop() {
 		intChan := make(chan os.Signal, 1)
 		signal.Notify(intChan, os.Interrupt, syscall.SIGTERM)
 		go func() {
-			<-intChan
-			t.reqBox.Set(reqQuit, nil)
+			for {
+				s := <-intChan
+				// Don't quit by SIGINT while executing because it should be for the executing command and not for fzf itself
+				if !(s == os.Interrupt && t.executing) {
```
Comment (junegunn) [inline src/terminal.go:1849]: This will generate a race condition warning.

```sh
rm /tmp/race.*; GORACE="log_path=/tmp/race" go run -race main.go --bind 'ctrl-l:execute:sleep 10'; cat /tmp/race.*
```

```
==================
WARNING: DATA RACE
Read at 0x00c000100d18 by goroutine 13:
  github.com/junegunn/fzf/src.(*Terminal).Loop.func1()
      /Users/jg/gdrive/sync/projects/fzf/src/terminal.go:1849 +0xe7

Previous write at 0x00c000100d18 by goroutine 10:
  github.com/junegunn/fzf/src.(*Terminal).executeCommand()
      /Users/jg/gdrive/sync/projects/fzf/src/terminal.go:1718 +0x509
  github.com/junegunn/fzf/src.(*Terminal).Loop.func17()
      /Users/jg/gdrive/sync/projects/fzf/src/terminal.go:2233 +0x6bcf
  github.com/junegunn/fzf/src.(*Terminal).Loop.func16()
      /Users/jg/gdrive/sync/projects/fzf/src/terminal.go:2223 +0xdb
  github.com/junegunn/fzf/src.(*Terminal).Loop()
      /Users/jg/gdrive/sync/projects/fzf/src/terminal.go:2628 +0x11dd

Goroutine 13 (running) created at:
  github.com/junegunn/fzf/src.(*Terminal).Loop()
      /Users/jg/gdrive/sync/projects/fzf/src/terminal.go:1845 +0x16b

Goroutine 10 (running) created at:
  github.com/junegunn/fzf/src.Run()
      /Users/jg/gdrive/sync/projects/fzf/src/core.go:220 +0xe5e
  main.main()
      /Users/jg/gdrive/sync/projects/fzf/main.go:13 +0xae
==================
```

Let's use an [AtomicBool](https://github.com/bitterfox/fzf/blob/sigint_while_executing/src/util/atomicbool.go).

**Review by junegunn — CHANGES_REQUESTED** [review]

File: src/terminal.go [hunk 2]
```diff
@@ -1837,8 +1843,13 @@ func (t *Terminal) Loop() {
 		intChan := make(chan os.Signal, 1)
 		signal.Notify(intChan, os.Interrupt, syscall.SIGTERM)
 		go func() {
-			<-intChan
-			t.reqBox.Set(reqQuit, nil)
+			for {
+				s := <-intChan
```
Comment (junegunn) [inline src/terminal.go:1847]: We can simplify this to `for s := range intChan {`.

* https://gobyexample.com/range-over-channels

File: src/terminal.go (hunk 1 above)
Comment (bitterfox) [reply src/terminal.go]: Thank you. I updated to use AtomicBool

**Comment by junegunn** [comment]
Merged, thanks!
