### PR TITLE
Make ctrl-alt-h a synonym of ctrl-alt-backspace on non-Windows environment

### LINKED ISSUE #4587: `ctrl-alt-h` binding is broken
### Checklist

- [x] I have read through the manual page (`man fzf`)
- [x] I have searched through the existing issues
- [x] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.66.1 (c1b259c0)

### OS

- [x] Linux
- [ ] macOS
- [ ] Windows
- [x] Etc.

### Shell

- [x] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

```bash
FZF_DEFAULT_OPTS= fzf --bind ctrl-alt-h:backward-kill-word
```
The `ctrl-alt-h` binding does not work as expected.

### PR DESCRIPTION
**Pull request by junegunn**
Fix #4587

### CODE REVIEW

File: src/options.go [hunk 1]
```diff
@@ -1217,7 +1217,11 @@ func parseKeyChords(str string, message string) (map[tui.Event]string, []tui.Eve
 		default:
 			runes := []rune(key)
 			if len(key) == 10 && strings.HasPrefix(lkey, "ctrl-alt-") && isAlphabet(lkey[9]) {
-				evt := tui.CtrlAltKey(rune(key[9]))
+				r := rune(key[9])
+				evt := tui.CtrlAltKey(r)
+				if r == 'h' && !util.IsWindows() {
+					evt = tui.CtrlAltBackspace.AsEvent()
+				}
```
Comment (junegunn) [inline src/options.go]: The problem with this approach is that `ctrl-alt-backspace` binding can inadvertently shadow `ctrl-alt-h` binding.

```sh
fzf --bind ctrl-alt-h:up+up,ctrl-alt-backspace:up
```

But I don't have a better idea at this point.
