### PR TITLE
fix(terminal): correct display width calculation with maxWidth

### LINKED ISSUE #4593: Multi-character ellipsis leaves right-side artifacts with freeze-right option enabled
### Checklist

- [x] I have read through the manual page (`man fzf`)
- [x] I have searched through the existing issues
- [x] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.67.0 (2ab923f3)

### OS

- [ ] Linux
- [x] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [x] zsh
- [ ] fish

## Problem / Steps to reproduce

Long ellipsis causes character artifact 

issue started with: 3f499f055ee04fa9a3f0691b00c1088da2bab475

### to reproduce

1. Run the command below; ellipsis should be more than 2 chars
2. Keep pressing the up arrow key 
3. Notice the chars on the right side remain visible 

```bash
{
  seq 30
  printf '%.0sg' {1..1000}
  echo
  seq 32 100
} |
  FZF_DEFAULT_OPTS='' fzf \
    --ellipsis='...' \
    --freeze-right 1
```

Image

---

workaround: trim the ellipsis to 2 dots only

### PR DESCRIPTION
**Pull request by LangLangBart**
fix #4593

---

reproduction described in the ref ticket

~~is a test needed ?~~

### CODE REVIEW

**Comment by junegunn** [comment]
> is a test needed ?

Preferably, yes, to avoid future regressions. I know writing an integration test can be not so straightforward, so I can add it for you if that's easier.

**Comment by LangLangBart** [comment]
> Preferably, yes, to avoid future regressions.

An attempt was made... 😬

File: test/test_core.rb [hunk 1]
```diff
@@ -1235,6 +1235,21 @@ def test_freeze_right_exceed_range_with_freeze_left
...
 
+  def test_freeze_right_with_ellipsis_and_scrolling
+    tmux.send_keys "{ seq 30; ruby -e 'print \"g\"*1000, \"\\n\"'; seq 32 100; } | #{FZF} --ellipsis='...' --freeze-right 1", :Enter
+    tmux.until { |lines| assert_equal '  100/100', lines[-2] }
+    tmux.send_keys(*Array.new(30) { :Up })
+    tmux.until do |lines|
+      line = lines.find { |l| l.start_with?('>') }
+      assert_match(/> \.\.\.g+$/, line)
+    end
+    tmux.send_keys :Up
```
Comment (junegunn) [inline test/test_core.rb]: Thanks, but I think this doesn't necessarily cause scrolling.

How about triggering `offset-up` action?

```sh
{ seq 6; ruby -e 'print "g"*1000, "\n"'; seq 8 100; } |
  fzf --ellipsis 777 --freeze-right 1 --scroll-off 0 --bind a:offset-up
````

- Press `a` 6 times, and see if there's a line starting with `> 777ggg`
- And there's only one line that ends with `g`

Comment (LangLangBart) [reply test/test_core.rb]: Adjusted the test as you described.

**Review by junegunn — APPROVED** [review]
LGTM!

**Comment by junegunn** [comment]
Merged, thanks!
