### PR TITLE
Fix zsh history widget when `sh_glob` option is on

### LINKED ISSUE #4712: `sh_glob` zsh option breaks CTRL-R history widget
### Checklist

- [x] I have read through the manual page (`man fzf`)
- [x] I have searched through the existing issues
- [x] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.70.0 (Homebrew)

### OS

- [x] Linux
- [x] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [x] zsh
- [ ] fish

### Problem / Steps to reproduce

1. In a fresh zsh install, run `source <(fzf --zsh)`.
2. Run any command. `echo foo` is fine.
3. Press Ctrl-R to open `fzf-history-widget`. Select the previous command and see that it works fine.
4. Run `setopt sh_glob` to enable the [`SH_GLOB` option](https://zsh.sourceforge.io/Doc/Release/Options.html#:~:text=SH%5FGLOB,ksh%2E).
5. Press Ctrl-R to open `fzf-history-widget`. Select a command and see that it includes the command number, which requires you to edit the command before it can be run.

I experience this with `zsh` 5.9 on Ubuntu, Debian, and macOS.

Screencast:

https://github.com/user-attachments/assets/9763f769-51ed-4b6d-9b94-4c3c2361bf3c

I _think_ this can be fixed by adding `no_sh_glob` to the command-specific options. This patch works for me:

```diff
diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
index 14c31de7..b4cbb4d5 100644
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -129,7 +129,7 @@ fi
 # CTRL-R - Paste the selected command from history into the command line
 fzf-history-widget() {
   local selected extracted_with_perl=0
-  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases no_glob no_ksharrays extendedglob 2> /dev/null
+  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases no_glob no_ksharrays no_sh_glob extendedglob 2> /dev/null
   # Ensure the module is loaded if not already, and the required features, such
   # as the associative 'history' array, which maps event numbers to full history
   # lines, are set. Also, make sure Perl is installed for multi-line output.
```

Happy to submit a PR.

### PR DESCRIPTION
**Pull request by EvanHahn**
Fixes #4712.

The CTRL-R history widget failed in zsh when [zsh's `sh_glob` option][0] was on. This fixes that by disabling the option locally, like we disable other options.

[0]: https://zsh.sourceforge.io/Doc/Release/Options.html#:~:text=SH%5FGLOB,ksh%2E

### CODE REVIEW

**Comment by EvanHahn** [comment]
CI failures seem unrelated.

File: test/test_shell_integration.rb [hunk 1]
```diff
@@ -158,6 +158,23 @@ def test_ctrl_r_abort
       tmux.until { |lines| assert lines[-1]&.start_with?(query) }
     end
   end
+
+  def test_ctrl_r_zsh_sh_glob
+    skip("this is a zsh-specific test") unless shell == :zsh
```
Comment (LangLangBart) [inline test/test_shell_integration.rb]: moving it into `TestZsh` removes the condition check in the shared module and groups them together with other zsh ctrl-r tests 

```diff
--- a/test/test_shell_integration.rb
+++ b/test/test_shell_integration.rb
@@ -938,4 +938,6 @@ class TestZsh < TestBase
 
   test_perl_and_awk 'ctrl_r_multiline_index_collision' do
+    # Verify selection works with conflicting options
+    tmux.send_keys 'setopt ksharrays sh_glob', :Enter
     # Leading number in multi-line history content is not confused with index
     prepare_ctrl_r_test
```

Comment (EvanHahn) [reply test/test_shell_integration.rb]: Ah, I missed that! Fixed in 40dcf8eedbfe8f2172b398b908dfc9897639239b.

**Comment by EvanHahn** [comment]
I addressed comments. (I didn't rebase or squash. Let me know if you want me to.)

**Review by junegunn — APPROVED** [review]

**Comment by junegunn** [comment]
Merged, thanks for the contribution @EvanHahn. And thank you @LangLangBart for the thorough review.

**Comment by LangLangBart** [comment]
> thorough

😬 thx, i noticed the typo
